# Generated by Django 2.0.2 on 2018-02-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_githubrankedrepo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githublanguage',
            old_name='language',
            new_name='name',
        ),
    ]
